export const siteConfig = {
  title: "Dream Blog",
  authorName: "Blog Author",
  bio: "A personal space for code, science, and thoughts.",
  navTitle: "Dream",
  navSuffix: "·",
  navAfter: "Blog",
  avatarUrl: "/bg/1.jpg",
  useGradient: false,
  themeColors: ["#a18cd1", "#fbc2eb", "#a1c4fd", "#c2e9fb"],
  bgImages: [
    "/bg/1.jpg", "/bg/2.jpg", "/bg/3.jpg",
    "/bg/4.jpg", "/bg/5.PNG", "/bg/6.png",
  ],
  defaultPostCover: "/bg/1.jpg",
  photoWallImage: "/bg/1.jpg",
  cloudMusicIds: ["1809646618"],
  social: {
    github: "",
    email: "",
  },
  counts: { photos: 0 },
  chatterTitle: "杂谈",
  chatterDescription: "代码、学术与生活的碎片记录",
  danmakuList: ["Hello!", "Welcome to my blog~"],
  buildDate: "2026-01-01T00:00:00",
  footerBadges: [],
  icpConfig: { name: "", link: "" },
};
